# Generated by Django 6.0 on 2026-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('passos', models.IntegerField(default=0)),
                ('exercicio_min', models.FloatField(default=0.0)),
                ('hr_media', models.FloatField(default=0.0)),
                ('sono_profundo_min', models.FloatField(default=0.0)),
                ('alerta', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
