# Generated by Django 6.0 on 2026-04-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DiarioSaude',
        ),
    ]
