# Generated by Django 5.2.9 on 2026-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_analysis', '0002_metricasaude_delete_diariosaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricasaude',
            name='alerta_detalhado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricasaude',
            name='cidade',
            field=models.CharField(default='Braga', max_length=100),
        ),
        migrations.AddField(
            model_name='metricasaude',
            name='cor_exibicao',
            field=models.CharField(default='#81d4fa', max_length=20),
        ),
        migrations.AddField(
            model_name='metricasaude',
            name='emoji_estado',
            field=models.CharField(default='🌙', max_length=10),
        ),
        migrations.AddField(
            model_name='metricasaude',
            name='hora_sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricasaude',
            name='hora_sunset',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricasaude',
            name='titulo_classificacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='metricasaude',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metricasaude',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
